var updateInterval=3;var justSelected=false;var dragZoneName="";var lastUpdate=0;var currZone="";var currZoneLU=0;var currZoneIsGroup=false;var volSliderInUse=false;var mainVolOld=-1;var selectedQueue="";var prevBroswerPath=new Array('');var globalUpdater=new PeriodicalExecuter(ajaxUpdate,updateInterval);var interactiveDrop=new Array();function sprintf(fstring)
{var pad=function(str,ch,len)
{var ps='';for(var i=0;i<Math.abs(len);i++)ps+=ch;return len>0?str+ps:ps+str;}
var processFlags=function(flags,width,rs,arg)
{var pn=function(flags,arg,rs)
{if(arg>=0)
{if(flags.indexOf(' ')>=0)rs=' '+rs;else if(flags.indexOf('+')>=0)rs='+'+rs;}
else
rs='-'+rs;return rs;}
var iWidth=parseInt(width,10);if(width.charAt(0)=='0')
{var ec=0;if(flags.indexOf(' ')>=0||flags.indexOf('+')>=0)ec++;if(rs.length<(iWidth-ec))rs=pad(rs,'0',rs.length-(iWidth-ec));return pn(flags,arg,rs);}
rs=pn(flags,arg,rs);if(rs.length<iWidth)
{if(flags.indexOf('-')<0)rs=pad(rs,' ',rs.length-iWidth);else rs=pad(rs,' ',iWidth-rs.length);}
return rs;}
var converters=new Array();converters['c']=function(flags,width,precision,arg)
{if(typeof(arg)=='number')return String.fromCharCode(arg);if(typeof(arg)=='string')return arg.charAt(0);return'';}
converters['d']=function(flags,width,precision,arg)
{return converters['i'](flags,width,precision,arg);}
converters['u']=function(flags,width,precision,arg)
{return converters['i'](flags,width,precision,Math.abs(arg));}
converters['i']=function(flags,width,precision,arg)
{var iPrecision=parseInt(precision);var rs=((Math.abs(arg)).toString().split('.'))[0];if(rs.length<iPrecision)rs=pad(rs,' ',iPrecision-rs.length);return processFlags(flags,width,rs,arg);}
converters['E']=function(flags,width,precision,arg)
{return(converters['e'](flags,width,precision,arg)).toUpperCase();}
converters['e']=function(flags,width,precision,arg)
{iPrecision=parseInt(precision);if(isNaN(iPrecision))iPrecision=6;rs=(Math.abs(arg)).toExponential(iPrecision);if(rs.indexOf('.')<0&&flags.indexOf('#')>=0)rs=rs.replace(/^(.*)(e.*)$/,'$1.$2');return processFlags(flags,width,rs,arg);}
converters['f']=function(flags,width,precision,arg)
{iPrecision=parseInt(precision);if(isNaN(iPrecision))iPrecision=6;rs=(Math.abs(arg)).toFixed(iPrecision);if(rs.indexOf('.')<0&&flags.indexOf('#')>=0)rs=rs+'.';return processFlags(flags,width,rs,arg);}
converters['G']=function(flags,width,precision,arg)
{return(converters['g'](flags,width,precision,arg)).toUpperCase();}
converters['g']=function(flags,width,precision,arg)
{iPrecision=parseInt(precision);absArg=Math.abs(arg);rse=absArg.toExponential();rsf=absArg.toFixed(6);if(!isNaN(iPrecision))
{rsep=absArg.toExponential(iPrecision);rse=rsep.length<rse.length?rsep:rse;rsfp=absArg.toFixed(iPrecision);rsf=rsfp.length<rsf.length?rsfp:rsf;}
if(rse.indexOf('.')<0&&flags.indexOf('#')>=0)rse=rse.replace(/^(.*)(e.*)$/,'$1.$2');if(rsf.indexOf('.')<0&&flags.indexOf('#')>=0)rsf=rsf+'.';rs=rse.length<rsf.length?rse:rsf;return processFlags(flags,width,rs,arg);}
converters['o']=function(flags,width,precision,arg)
{var iPrecision=parseInt(precision);var rs=Math.round(Math.abs(arg)).toString(8);if(rs.length<iPrecision)rs=pad(rs,' ',iPrecision-rs.length);if(flags.indexOf('#')>=0)rs='0'+rs;return processFlags(flags,width,rs,arg);}
converters['X']=function(flags,width,precision,arg)
{return(converters['x'](flags,width,precision,arg)).toUpperCase();}
converters['x']=function(flags,width,precision,arg)
{var iPrecision=parseInt(precision);arg=Math.abs(arg);var rs=Math.round(arg).toString(16);if(rs.length<iPrecision)rs=pad(rs,' ',iPrecision-rs.length);if(flags.indexOf('#')>=0)rs='0x'+rs;return processFlags(flags,width,rs,arg);}
converters['s']=function(flags,width,precision,arg)
{var iPrecision=parseInt(precision);var rs=arg;if(rs.length>iPrecision)rs=rs.substring(0,iPrecision);return processFlags(flags,width,rs,0);}
farr=fstring.split('%');retstr=farr[0];fpRE=/^([-+ #]*)(\d*)\.?(\d*)([cdieEfFgGosuxX])(.*)$/;for(var i=1;i<farr.length;i++)
{fps=fpRE.exec(farr[i]);if(!fps)continue;if(arguments[i]!=null)retstr+=converters[fps[4]](fps[1],fps[2],fps[3],arguments[i]);retstr+=fps[5];}
return retstr;}
function callInProgress(xmlhttp){switch(xmlhttp.readyState){case 1:case 2:case 3:return true;break;default:return false;break;}}
Ajax.Responders.register({onCreate:function(request){request['timeoutId']=window.setTimeout(function(){if(callInProgress(request.transport)){request.transport.abort();if(request.options['onFailure']){request.options['onFailure'](request.transport,request.json);}}},5000);},onComplete:function(request){window.clearTimeout(request['timeoutId']);}});function initWebKitSearch(){if(navigator.userAgent.indexOf("AppleWebKit")!=-1){var theSearchField=document.getElementById('q');theSearchField.setAttribute('type','search');theSearchField.setAttribute('autosave','saved.data');theSearchField.setAttribute('results','5');theSearchField.setAttribute('placeholder','');}}
function ajaxUpdate(){var myAjax=new Ajax.Request('data/init.json',{method:'get',onComplete:processInit});delete myAjax;}
function processInit(ajaxReq){var swcData=eval('( '+ajaxReq.responseText+' )');if(swcData.init.last_update>lastUpdate){lastUpdate=swcData.init.last_update;ajaxUpdateZones();}
if($('initMessage').innerHTML=='')drawVersionInfo(swcData.init.version);delete swcData;}
function drawVersionInfo(swcVersion){$('initMessage').innerHTML='<span class="name">User Interface<\/span><span class="content">Version 0.1.3<br />Xiao Yu<\/span><span class="name">Perl Controller<\/span><span class="content">Version '+swcVersion+'<br />Andy<\/span><span class="name">Update Interval<\/span><span class="content">'+updateInterval+' Seconds<\/span>';}
function ajaxUpdateZones(){var myAjax=new Ajax.Request('data/zones.json',{method:'get',onComplete:processZones});delete myAjax;}
function processZones(ajaxReq){var swcData=eval('( '+ajaxReq.responseText.replace('},]','}]')+' )');while(swcData.zone[0].last_update=="")swcData.zone.shift();if($('volumeWindow').style.display=='none')drawZones(swcData);drawVolume(swcData);delete swcData;}
function drawVolume(swcData){if(volSliderInUse)return true;var mainVol=0;var target=$('volumeWindow');var mainVolNum=0;var outHTML="<h1>Volume Controls<\/h1><div class='scroller'>";var outJS="";var currZoneUpdate=false;var currZoneFound=false;for(var i=0;i<swcData.zone.length;i++){muteStatus="";if(swcData.zone[i].muted==1)muteStatus=" class='mute'";outHTML+="<div id='vol-"+swcData.zone[i].id+"'"+muteStatus+"><h2>"+swcData.zone[i].name+"<\/h2><div class='volController'><span onclick='javascript:changeMute(\""+swcData.zone[i].id+"\")'><!-- --><\/span><div id='volBar-"+swcData.zone[i].id+"' class='volBar'><div id='volHandel-"+swcData.zone[i].id+"' class='volHandel'><!-- --><\/div><\/div><\/div><\/div>";outJS+="slider_"+swcData.zone[i].id+" = new Control.Slider('volHandel-"+swcData.zone[i].id+"','volBar-"+swcData.zone[i].id+"',{sliderValue:"+(swcData.zone[i].volume/100)+", onSlide:function(v){volSliderInUse = true}, onChange:function(v){changeVolume(v, '"+swcData.zone[i].id+"')}});";if((swcData.zone[i].id==currZone)||(swcData.zone[i].parent_zone==currZone)){mainVol+=(swcData.zone[i].volume/100);mainVolNum++;}
if((swcData.zone[i].id==currZone)&&(swcData.zone[i].is_child==0)){currZoneFound=true;if(swcData.zone[i].last_update>currZoneLU){currZoneUpdate=true;currZoneLU=swcData.zone[i].last_update;}}}
if(target.style.display!='none'){target.innerHTML=outHTML+"<\/div>";eval(outJS);}
if(currZoneFound){if(mainVolNum>1){currZoneIsGroup=true;mainVol/=mainVolNum;$('lblVolume').innerHTML="Group Volume";}else{currZoneIsGroup=false;$('lblVolume').innerHTML="Volume";}
if(typeof(slider_main)=='undefined'){slider_main=new Control.Slider('mainVolHandel','mainVolBar',{sliderValue:mainVol,onSlide:function(v){volSliderInUse=true},onChange:function(v){changeVolume(v,'main')}});}else{mainVolOld=-1;slider_main.setValue(mainVol);slider_main.setEnabled();}
$('mainVolHandel').className='enabled';}else{currZone="";resetIsonos();}
if(currZoneUpdate)ajaxUpdateCurrZone();}
function changeVolume(newVal,zoneID){volSliderInUse=false;if(zoneID=='main'){if(currZone=="")return true;if(mainVolOld==-1){mainVolOld=Math.round(newVal*100);return true;}
if(currZoneIsGroup){var myAjax=new Ajax.Request('data/zones.json',{method:'get',onComplete:function(d){changeGroupVol(d,Math.round(newVal*100)-mainVolOld)}});delete myAjax;}else{var myAjax=new Ajax.Request('data/zones.json',{method:'get',parameters:'action=SetVolume&zone='+currZone+'&volume='+Math.round(newVal*100),onComplete:processZones});delete myAjax;}}else{var myAjax=new Ajax.Request('data/zones.json',{method:'get',parameters:'action=SetVolume&zone='+zoneID+'&volume='+Math.round(newVal*100),onComplete:processZones});delete myAjax;}}
function changeGroupVol(ajaxReq,diff){var swcData=eval('( '+ajaxReq.responseText.replace('},]','}]')+' )');for(var i=0;i<swcData.zone.length;i++){if((swcData.zone[i].id==currZone)||(swcData.zone[i].parent_zone==currZone)){var newVol=Math.max(parseInt(swcData.zone[i].volume)+diff,0);var myAjax=new Ajax.Request('data/init.json',{method:'get',parameters:'action=SetVolume&zone='+swcData.zone[i].id+'&volume='+Math.min(newVol,100)});delete myAjax;}}
delete swcData;ajaxUpdateZones();}
function changeMute(zoneID){var action='';if($('vol-'+zoneID).className=='mute'){action='action=MuteOff&zone=';$('vol-'+zoneID).className='';}else{action='action=MuteOn&zone=';$('vol-'+zoneID).className='mute';}
var myAjax=new Ajax.Request('data/zones.json',{method:'get',parameters:action+zoneID,onComplete:processZones});delete myAjax;}
function drawZones(swcData){var outHTML="<div id='allZones' title='Drag and drop on to a Zone Player to link all other players to that zone.'><!-- --><\/div><div id='dropZone' title='Drag a Zone Player here to drop it from the group.'><!-- --><\/div><div class='clear'><!-- --><\/div>";var outJS="new Draggable('allZones',{ghosting: true, revert:true, starteffect:function(e){zoneDragStart(e)}, endeffect:function(e){zoneDragEnd(e)}}); Droppables.add('dropZone', {hoverclass:'hover',accept:'zone',onDrop:function(e){zoneDrop(e);}}); ";interactiveDrop.push("dropZone");for(var i=0;i<swcData.zone.length;i++){activeStatus="";if(swcData.zone[i].id==currZone)activeStatus=" active";modeStatus="zoneMode"+swcData.zone[i].mode;if(swcData.zone[i].is_child==0){outHTML+="<div id='drop-"+swcData.zone[i].id+"' class='zoneTab"+activeStatus+"' onclick='javascript:zoneSelect(\""+swcData.zone[i].id+"\")'><div class='"+modeStatus+"'><!-- --><\/div>";outJS+="Droppables.add('drop-"+swcData.zone[i].id+"', {hoverclass:'hover',onDrop:function(e){zoneLink(e,'"+swcData.zone[i].id+"')}}); ";interactiveDrop.push("drop-"+swcData.zone[i].id);}
outHTML+="<span id='drag-"+swcData.zone[i].id+"' class='zone "+swcData.zone[i].icon.substr(18)+"'>"+swcData.zone[i].name+"<\/span>";outJS+=" new Draggable('drag-"+swcData.zone[i].id+"',{ghosting: true, revert:true, starteffect:function(e){zoneDragStart(e)}, endeffect:function(e){zoneDragEnd(e)}}); ";if((i==swcData.zone.length-1)||(swcData.zone[i+1].is_child==0)){outHTML+="<\/div>";}}
$('zones').innerHTML='';Droppables.drops=[];$('zones').innerHTML=outHTML;eval(outJS);}
function zoneDragStart(e){var target=$(e);target.className+=" zoneDrag";dragZoneName=target.innerHTML;target.innerHTML="";}
function zoneDragEnd(e){var target=$(e);target.className=target.className.replace("zoneDrag","");target.innerHTML=dragZoneName;dragZoneName="";}
function zoneDrop(s){$('zones').innerHTML="<h2 class='loading'>loading<\/h2>";var myAjax=new Ajax.Request('data/zones.json',{method:'get',parameters:'action=Unlink&zone='+s.id.substr(5)+'&link='+s.id.substr(5),onComplete:processZones,onFailure:ajaxUpdateZones});delete myAjax;}
function zoneLink(s,t){$('zones').innerHTML="<h2 class='loading'>loading<\/h2>";var prams='action=Link&zone='+t+'&link='+s.id.substr(5);if(s.id=="allZones")prams='action=LinkAll&zone='+t;var myAjax=new Ajax.Request('data/zones.json',{method:'get',parameters:prams,onComplete:processZones,onFailure:ajaxUpdateZones});delete myAjax;}
function resetIsonos(){$('btnList').className='btnList0';$('btnPrev').className='btnPrev0';$('btnPlPu').className='btnPaus0';$('btnNext').className='btnNext0';$('btnShuf').className='btnShuf0';$('btnRept').className='btnRept0';$('btnCler').className="btnCler0";$('btnSave').className="btnSave0";$('btnList').className="btnList0";$('browser').style.display="none";$('q').disabled='disabled';$('song').innerHTML="&nbsp;";$('artist').innerHTML="&nbsp;";$('album').innerHTML="&nbsp;";$('track').innerHTML="&nbsp;";$('length').innerHTML="&nbsp;";$('nSong').innerHTML="&nbsp;";$('nArtist').innerHTML="&nbsp;";$('nAlbum').innerHTML="&nbsp;";$('albumart').innerHTML="<h1>Album Art<\/h1><img src='inc/noartwork.png' height='200' \/>";$('fauxTblQueue').innerHTML="&nbsp;";$('mainVolHandel').className='disabled';if(typeof(slider_main)!='undefined'){mainVolOld=-1;slider_main.setValue(0);slider_main.setDisabled();}}
function ajaxUpdateCurrZone(){if(currZone=="")return false;var myAjax=new Ajax.Request('data/zone_info.json',{method:'get',parameters:'zone='+currZone,onComplete:processCurrZone});delete myAjax;}
function processCurrZone(ajaxReq){var swcData=eval('( '+ajaxReq.responseText.replace('},]','}]')+' )');drawControlBtns(swcData);drawSongInfo(swcData);drawSongQueue(swcData);delete swcData;}
function drawControlBtns(swcData){if(swcData.current_zone.song.type=='song'){if(swcData.current_zone.song.track_num<=1){$('btnPrev').className='btnPrev0';}else{$('btnPrev').className='btnPrev1';}
if(swcData.current_zone.song.track_tot==0){$('btnPlPu').className='btnPlay0';}else{if(swcData.current_zone.status.playback==1){$('btnPlPu').className='btnPaus1';}else{$('btnPlPu').className='btnPlay1';}}
if(swcData.current_zone.next.name==''){$('btnNext').className='btnNext0';}else{$('btnNext').className='btnNext1';}
if(swcData.current_zone.status.shuffle==0){$('btnShuf').className='btnShuf1';}else{$('btnShuf').className='btnShuf2';}
if(swcData.current_zone.status.repeat==0){$('btnRept').className='btnRept1';}else{$('btnRept').className='btnRept2';}}else{$('btnPrev').className='btnPrev0';if(swcData.current_zone.status.playback==1){$('btnPlPu').className='btnPaus1';}else{$('btnPlPu').className='btnPlay1';}
$('btnNext').className='btnNext0';$('btnShuf').className='btnShuf0';$('btnRept').className='btnRept0';}
$('q').disabled='';if($('btnList').className=='btnList0')$('btnList').className='btnList1';}
function drawSongInfo(swcData){if(swcData.current_zone.song.name=='')swcData.current_zone.song.name='&nbsp;';$('song').innerHTML=swcData.current_zone.song.name;if(swcData.current_zone.song.artist=='')swcData.current_zone.song.artist='&nbsp;';$('artist').innerHTML=swcData.current_zone.song.artist;if(swcData.current_zone.song.album=='')swcData.current_zone.song.album='&nbsp;';$('album').innerHTML=swcData.current_zone.song.album;if(swcData.current_zone.song.track_tot==0){$('track').innerHTML='&nbsp;';}else{$('track').innerHTML=swcData.current_zone.song.track_num+' of '+swcData.current_zone.song.track_tot;}
if(swcData.current_zone.song.length>0){var sec=swcData.current_zone.song.length%60;var min=(swcData.current_zone.song.length-sec)/60;$('length').innerHTML=sprintf("%d:%02d",min,sec);}else{$('length').innerHTML="&nbsp;";}
if(swcData.current_zone.song.artwork==""){$('albumart').innerHTML="<h1>Album Art<\/h1><img src='inc/noartwork.png' height='200' \/>";}else{if($('albumart').innerHTML!="<h1>Album Art<\/h1><img src='"+swcData.current_zone.song.artwork+"' height='200' \/>")$('albumart').innerHTML="<h1>Album Art<\/h1><img src='"+swcData.current_zone.song.artwork+"' height='200' \/>";}
if(swcData.current_zone.next.name=='')swcData.current_zone.next.name='&nbsp;';$('nSong').innerHTML=swcData.current_zone.next.name;if(swcData.current_zone.next.artist=='')swcData.current_zone.next.artist='&nbsp;';$('nArtist').innerHTML=swcData.current_zone.next.artist;if(swcData.current_zone.next.album=='')swcData.current_zone.next.album='&nbsp;';$('nAlbum').innerHTML=swcData.current_zone.next.album;}
function drawSongQueue(swcData){var evenStatus=" even";var songQueue="";for(var i=0;i<swcData.current_zone.queue.length;i++){rowStatus="";if(swcData.current_zone.queue[i].status=="/playing.gif")rowStatus=' dspPlaying';if(swcData.current_zone.queue[i].status=="/paused.gif")rowStatus=' dspPaused';if(evenStatus==""){evenStatus=" even";}else{evenStatus="";}
if((swcData.current_zone.queue[i].name+"|"+swcData.current_zone.queue[i].id)==selectedQueue)evenStatus+=" selected";songQueue+="<div class='fauxTblRow"+evenStatus+"' onclick='javascript:tableSelect(this)' ondblclick='javascript:queuePlay(\""+swcData.current_zone.queue[i].id+"\")'><div class='fauxTblStatus"+rowStatus+"'>&nbsp;<\/div><div class='fauxTblInfo' title='"+swcData.current_zone.queue[i].name+"'>"+swcData.current_zone.queue[i].name+"<\/div><div class='fauxTblAction btnRemove' onclick='javascript:queueRemove(\""+swcData.current_zone.queue[i].id+"\")'>&nbsp;<\/div><\/div>";}
$('fauxTblQueue').innerHTML=songQueue;if(songQueue==''){$('btnCler').className="btnCler0";$('btnSave').className="btnSave0";}else{$('btnCler').className="btnCler1";$('btnSave').className="btnSave1";}}
function zoneSelect(zoneID){if(currZone!=zoneID){if($('btnList').className=='btnList2')btnClick('btnList');currZoneLU=0;mainVolOld=-1;if(typeof($('btnSavC'))!='undefined')btnClick('btnSavC');if((currZone=='')&&($('btnInfo').className=='btnInfo2'))btnClick('btnInfo');currZone=zoneID;ajaxUpdateZones();}}
function tableUnselect(r){if(!justSelected){r=$(r);for(var i=0;i<r.childNodes.length;i++){if(r.childNodes[i].nodeName=="DIV"){r.childNodes[i].className=r.childNodes[i].className.replace("selected","");}}
selectedQueue="";}
justSelected=false;}
function tableSelect(r){tableUnselect(r.parentNode);r.className+=" selected";justSelected=true;if(r.parentNode.id=="fauxTblQueue")selectedQueue=document.getElementsByClassName('fauxTblInfo',r)[0].title+"|"+r.ondblclick.toString().split("\"",2)[1];}
function queuePlay(arg){var myAjax=new Ajax.Request('data/init.json',{method:'get',parameters:"action=Seek&zone="+currZone+"&queue="+arg,onComplete:function(d){var myAjax=new Ajax.Request('data/zone_info.json',{method:'get',parameters:"action=Play&zone="+currZone,onComplete:processCurrZone,onFailure:ajaxUpdateZones});delete myAjax;}});delete myAjax;}
function queueRemove(arg){var myAjax=new Ajax.Request('data/zone_info.json',{method:'get',parameters:"action=Remove&zone="+currZone+"&queue="+arg,onComplete:processCurrZone,onFailure:ajaxUpdateZones});delete myAjax;}
function btnClick(btnID,noUpdate){if(typeof(noUpdate)=='undefined')noUpdate=false;var btn=$(btnID);var currClass=btn.className;if(currClass.substring(7,8)=='0')return false;switch(btnID){case'btnPrev':if(currZone=='')return false;var myAjax=new Ajax.Request('data/zone_info.json',{method:'get',parameters:'action=Previous&zone='+currZone,onComplete:processCurrZone,onFailure:ajaxUpdateZones});delete myAjax;break;case'btnPlPu':if(currZone=='')return false;var action='';if(currClass=='btnPaus1'){btn.className='btnPlay1';action='action=Pause&zone=';}else{btn.className='btnPaus1';action='action=Play&zone=';}
var myAjax=new Ajax.Request('data/zones.json',{method:'get',parameters:action+currZone,onComplete:processZones,onFailure:ajaxUpdateZones});delete myAjax;break;case'btnNext':if(currZone=='')return false;var myAjax=new Ajax.Request('data/zone_info.json',{method:'get',parameters:'action=Next&zone='+currZone,onComplete:processCurrZone,onFailure:ajaxUpdateZones});delete myAjax;break;case'btnList':if(currZone=='')return false;if(currClass=='btnList1'){var timeout=1;if($('btnPlug').className=='btnPlug2'){btnClick('btnPlug');timeout=1000}
if($('btnInfo').className=='btnInfo2'){btnClick('btnInfo');timeout=1000}
setTimeout("Effect.BlindDown('browser');",timeout);if(!noUpdate)ajaxMusicSearch();btn.className='btnList2';}else{Effect.BlindUp('browser');btn.className='btnList1';}
break;case'btnShuf':if(currZone=='')return false;var action='';if(currClass=='btnShuf1'){btn.className='btnShuf2';action='action=ShuffleOn&zone=';}else{btn.className='btnShuf1';action='action=ShuffleOff&zone='}
var myAjax=new Ajax.Request('data/zone_info.json',{method:'get',parameters:action+currZone,onComplete:processCurrZone,onFailure:ajaxUpdateZones});delete myAjax;break;case'btnRept':if(currZone=='')return false;var action='';if(currClass=='btnRept1'){btn.className='btnRept2';action='action=RepeatOn&zone=';}else{btn.className='btnRept1';action='action=RepeatOff&zone=';}
var myAjax=new Ajax.Request('data/zone_info.json',{method:'get',parameters:action+currZone,onComplete:processCurrZone,onFailure:ajaxUpdateZones});delete myAjax;break;case'btnVolu':if(currClass=='btnVolu1'){Effect.BlindDown('volumeWindow');btn.className='btnVolu2';setTimeout('ajaxUpdateZones()',1000);}else{Effect.BlindUp('volumeWindow');btn.className='btnVolu1';setTimeout('ajaxUpdateZones()',1000);}
break;case'btnPlug':if(currClass=='btnPlug1'){var timeout=1;if($('btnList').className=='btnList2'){btnClick('btnList');timeout=1000}
if($('btnInfo').className=='btnInfo2'){btnClick('btnInfo');timeout=1000}
setTimeout("Effect.BlindDown('plugins');",timeout);btn.className='btnPlug2';}else{Effect.BlindUp('plugins');btn.className='btnPlug1';}
break;case'btnRidx':var myAjax=new Ajax.Request('data/init.json',{method:'get',parameters:'action=ReIndex'});delete myAjax;break;case'btnInfo':if(currClass=='btnInfo1'){var timeout=1;if($('btnList').className=='btnList2'){btnClick('btnList');timeout=1000}
if($('btnPlug').className=='btnPlug2'){btnClick('btnPlug');timeout=1000}
setTimeout("Effect.BlindDown('initWindow');",timeout);btn.className='btnInfo2';setTimeout("$('sosume').style.display='block';",1000);}else{$('sosume').style.display="none";Effect.BlindUp('initWindow');btn.className='btnInfo1';setTimeout("$('initMessage').innerHTML='';",1000);}
break;case'btnCler':if(currZone=='')return false;var myAjax=new Ajax.Request('data/zone_info.json',{method:'get',parameters:'action=RemoveAll&zone='+currZone,onComplete:processCurrZone,onFailure:ajaxUpdateZones});delete myAjax;break;case'btnSave':if(currZone=='')return false;$('queueOpt').innerHTML='<li id="btnSavC" class="btnSavC1" title="Don&#39;t save the current queue as a playlist." onclick="javascript:btnClick(\'btnSavC\');"><!-- --><\/li><li id="saveName"><form onsubmit="javascript:btnClick(\'btnSavK\'); return false;"><input id="queueSaveAs" type="text" value="Save current queue as..." /><\/form><\/li><li id="btnSavK" class="btnSavK1" title="Save the tracks in the queue as a SONOS playlist." onclick="javascript:btnClick(\'btnSavK\');"><!-- --><\/li>';$('queueSaveAs').focus();$('queueSaveAs').select();break;case'btnSavC':$('queueOpt').innerHTML='<li id="btnCler" class="btnCler1" title="Remove all tracks from the queue." onclick="javascript:btnClick(\'btnCler\');"><!-- --><\/li><li id="btnSave" class="btnSave1" title="Save the tracks in the queue as a SONOS playlist." onclick="javascript:btnClick(\'btnSave\');"><!-- --><\/li>';break;case'btnSavK':if(currZone==''){btnClick('btnSavC');return false;}
var arg="zone="+currZone+"&action=Save&savename="+encodeURIComponent($F('queueSaveAs'));$('saveName').innerHTML='<h2 class="loading">Saving Queue<\/h2>';var myAjax=new Ajax.Request('data/init.json',{method:'get',parameters:arg,onComplete:function(d){setTimeout("btnClick('btnSavC');",1000)}});delete myAjax;break;default:alert('Can not perform action!');return false;}}
function ajaxMusicSearch(arg){if(currZone=="")return false;if((arg=='')||(typeof(arg)=='undefined'))arg='zone='+currZone;$('fauxTblBrowser').innerHTML="<h2 class='loading'>loading<\/h2>";var myAjax=new Ajax.Request('data/zone_music_search.json',{method:'get',parameters:arg,onComplete:processMusicSearch});delete myAjax;}
function processMusicSearch(ajaxReq){var swcData=eval('( '+ajaxReq.responseText.replace('},]','}]')+' )');drawSongList(swcData);delete swcData;}
function drawSongList(swcData){var evenStatus=" even";var songList="";var iconArray=new Array();iconArray['A%3AARTIST']=new Array('dspArtist','dspArtist','dspAlbum','dspSong');iconArray['A%3AALBUM']=new Array('dspAlbum','dspAlbum','dspSong');iconArray['A%3AGENRE']=new Array('dspGenre','dspGenre','dspArtist','dspAlbum','dspSong');iconArray['A%3ACOMPOSER']=new Array('dspComposer','dspComposer','dspAlbum','dspSong');iconArray['A%3APLAYLISTS']=new Array('dspPlaylist','dspPlaylist','dspSong');iconArray['S%3A']=new Array('dspFolder');iconArray['R%3A']=new Array('dspRadio');iconArray['AI%3A']=new Array('dspLinein');iconArray['SQ%3A']=new Array('dspPlaylist');$('browserBar').innerHTML="<span class='back0'>&nbsp;<\/span>Music Browser";if((swcData.musiclib.path!='')&&(swcData.musiclib.path.substr(0,8)!='Search: ')){prevBroswerPath.push(swcData.musiclib.path);arg='zone='+currZone+'&mpath='+prevBroswerPath[prevBroswerPath.length-2];$('browserBar').innerHTML='<span class="back1" onclick="javascript:prevBroswerPath.pop(); prevBroswerPath.pop(); ajaxMusicSearch(\''+arg+'\')">&nbsp;<\/span>Music Browser';}else{prevBroswerPath.clear();prevBroswerPath.push('');}
if(swcData.musiclib.error!='')$('browserBar').innerHTML+=' &#8212; '+swcData.musiclib.error;for(var i=0;i<swcData.musiclib.song.length;i++){if(evenStatus==""){evenStatus=" even";}else{evenStatus="";}
var key='';var pos=0;var path=swcData.musiclib.song[i].path.split('%2F');if(path[0].split('%3A')[0]=='A'){key=path[0];pos=path.length-1;}else{key=path[0].split('%3A')[0]+'%3A';pos=0;}
var icon=iconArray[key][pos];if(typeof(icon)=='undefined')icon=iconArray[key][0];if(typeof(icon)=='undefined')icon='';dblClickAction=" ondblclick='javascript:ajaxMusicSearch(\""+swcData.musiclib.song[i].arg+"\")'";if(swcData.musiclib.song[i].type=='song'){dblClickAction="";icon='dspSong';}
var actions="";if(swcData.musiclib.path!='')actions="<div class='fauxTblAction btnAdd' onclick='javascript:listAction(\"add\", \""+swcData.musiclib.song[i].path+"\")'>&nbsp;<\/div><div class='fauxTblAction btnPlay' onclick='javascript:listAction(\"play\", \""+swcData.musiclib.song[i].path+"\")'>&nbsp;<\/div>";songList+="<div class='fauxTblRow"+evenStatus+"' onclick='javascript:tableSelect(this)'"+dblClickAction+"><div class='fauxTblStatus "+icon+"'>&nbsp;<\/div><div class='fauxTblInfo'>"+swcData.musiclib.song[i].name+"<\/div>"+actions+"<\/div>";}
$('fauxTblBrowser').innerHTML=songList;}
function listAction(action,path){var arg='zone='+currZone+'&mpath='+path;switch(action){case'play':arg+='&action=PlayMusic';break;case'add':arg+='&action=AddMusic';break;default:return false;}
var myAjax=new Ajax.Request('data/zone_info.json',{method:'get',parameters:arg,onComplete:processCurrZone,onFailure:ajaxUpdateZones});delete myAjax;}
function searchMusic(force){if(currZone=='')return false;var searchStr=$F('q');if(typeof(force)=='undefined')force=false;if(($('fauxTblBrowser').innerHTML=="<h2 class='loading'>loading<\/h2>")&&!force)return false;if((searchStr.length<3)&&!force)return false;if($('btnList').className=='btnList1')btnClick('btnList',true);ajaxMusicSearch('zone='+currZone+'&msearch='+encodeURIComponent(searchStr));}